services:
  damage_estimation_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mldnet.azurecr.io/damage_control_api:1.0.5
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    logging:
      driver: 'json-file'
#
##
#
# docker push mldnet.azurecr.io/damage_control_api:1.0.0
# docker login mldnet.azurecr.io
